stages:
  - builds
  - run
  - tests
  - cleanup

variables:
  CACHE_DIR: "/gpfs/f5/gfdl_o/scratch/oar.gfdl.ogrp-account/runner/cache/"

# Run for all stages
before_script:
  - echo Cache directory set to $CACHE_DIR
  - echo -e "\e[0Ksection_start:`date +%s`:before_script[collapsed=true]\r\e[0KPre-script"
  - git submodule init && git submodule update
  - cd MOM6-examples
  - echo -e "\e[0Ksection_end:`date +%s`:before_script\r\e[0K"

# Compiles
gnu:repro:
  stage: builds
  tags:
    - ncrc5
  script:
    - make -f tools/MRS/Makefile pipeline-build-repro-gnu

intel:repro:
  stage: builds
  tags:
    - ncrc5
  script:
    - make -f tools/MRS/Makefile pipeline-build-repro-intel

pgi:repro:
  stage: builds
  tags:
    - ncrc5
  script:
    - make -f tools/MRS/Makefile pipeline-build-repro-pgi

# Runs
run:
  stage: run
  tags:
    - ncrc5
  script:
    - make -f tools/MRS/Makefile stats-pipeline-run

# Tests
results:
  stage: tests
  tags:
    - ncrc5
  script:
    - cd ../regressions ; pwd
    - make -f ../MOM6-examples/tools/MRS/Makefile stats-pipeline-test

cleanup:
  stage: cleanup
  tags:
    - ncrc5
  before_script:
    - echo Skipping before-script
  script:
    - rm $CACHE_DIR/*$CI_PIPELINE_ID.tgz
