stages:
  - builds
  - run
  - tests
  - cleanup

variables:
  CACHE_DIR: "/lustre/f2/scratch/oar.gfdl.ogrp-account/runner/cache/"

# Run for all stages
before_script:
  - echo Cache directory set to $CACHE_DIR
  - echo -e "\e[0Ksection_start:`date +%s`:before_script[collapsed=true]\r\e[0KPre-script"
  - git submodule sync --recursive && git submodule update --init --recursive
  - make -f MOM6-examples/tools/MRS/Makefile stats-pipeline-pre-script
  - echo -e "\e[0Ksection_end:`date +%s`:before_script\r\e[0K"

# Compiles
gnu:repro:
  stage: builds
  tags:
    - ncrc4
  script:
    - env
    - make -f MOM6-examples/tools/MRS/Makefile stats-pipeline-build-repro-gnu

intel:repro:
  stage: builds
  tags:
    - ncrc4
  script:
    - make -f MOM6-examples/tools/MRS/Makefile stats-pipeline-build-repro-intel

pgi:repro:
  stage: builds
  tags:
    - ncrc4
  script:
    - make -f MOM6-examples/tools/MRS/Makefile stats-pipeline-build-repro-pgi

gnu:debug:
  stage: builds
  tags:
    - ncrc4
  script:
    - make -f MOM6-examples/tools/MRS/Makefile stats-pipeline-build-debug-gnu

# Runs
run:
  stage: run
  tags:
    - ncrc4
  script:
    - make -f MOM6-examples/tools/MRS/Makefile stats-pipeline-run

# Tests
gnu:non-symmetric:
  stage: tests
  tags:
    - ncrc4
  script:
    - make -f MOM6-examples/tools/MRS/Makefile stats-pipeline-test-gnu-nonsym

intel:non-symmetric:
  stage: tests
  tags:
    - ncrc4
  script:
    - make -f MOM6-examples/tools/MRS/Makefile stats-pipeline-test-intel-nonsym

pgi:non-symmetric:
  stage: tests
  tags:
    - ncrc4
  script:
    - make -f MOM6-examples/tools/MRS/Makefile stats-pipeline-test-pgi-nonsym

gnu:symmetric:
  stage: tests
  tags:
    - ncrc4
  script:
    - make -f MOM6-examples/tools/MRS/Makefile stats-pipeline-test-gnu-sym

intel:symmetric:
  stage: tests
  tags:
    - ncrc4
  script:
    - make -f MOM6-examples/tools/MRS/Makefile stats-pipeline-test-intel-sym

pgi:symmetric:
  stage: tests
  tags:
    - ncrc4
  script:
    - make -f MOM6-examples/tools/MRS/Makefile stats-pipeline-test-pgi-sym

gnu:layout:
  stage: tests
  tags:
    - ncrc4
  script:
    - make -f MOM6-examples/tools/MRS/Makefile stats-pipeline-test-gnu-layout

intel:layout:
  stage: tests
  tags:
    - ncrc4
  script:
    - make -f MOM6-examples/tools/MRS/Makefile stats-pipeline-test-intel-layout

pgi:layout:
  stage: tests
  tags:
    - ncrc4
  script:
    - make -f MOM6-examples/tools/MRS/Makefile stats-pipeline-test-pgi-layout

gnu:static:
  stage: tests
  tags:
    - ncrc4
  script:
    - make -f MOM6-examples/tools/MRS/Makefile stats-pipeline-test-gnu-static

gnu:restart:
  stage: tests
  tags:
    - ncrc4
  script:
    - make -f MOM6-examples/tools/MRS/Makefile stats-pipeline-test-gnu-restart

cleanup:
  stage: cleanup
  tags:
    - ncrc4
  script:
    - rm $CACHE_DIR/*$CI_PIPELINE_ID.tgz
